# Generated by Django 4.2.5 on 2023-09-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0002_alter_blogpost_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
